/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpoo.clases.ui;

/**
 *
 * @author Maestro 302
 */
public class SistemaCurricular extends javax.swing.JFrame {

    /**
     * Creates new form SistemaCurricular
     */
    public SistemaCurricular() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuArchivoExportar = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuArchivoSalir = new javax.swing.JMenuItem();
        menuMantenedores = new javax.swing.JMenu();
        menuMantenedoresAlumnos = new javax.swing.JMenuItem();
        menuMantenedoresDocentes = new javax.swing.JMenuItem();
        menuMantenedoresAdministrativos = new javax.swing.JMenuItem();
        menuMantenedoresAuxiliares = new javax.swing.JMenuItem();
        menuInformes = new javax.swing.JMenu();
        menuInformeNotas = new javax.swing.JMenuItem();
        menuInformeAsistencia = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuInformeMatricula = new javax.swing.JMenuItem();
        menuInformeMensualidad = new javax.swing.JMenuItem();
        menuProcesos = new javax.swing.JMenu();
        menuProcesosNotas = new javax.swing.JMenuItem();
        menuProcesosAsistencia = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuProcesosMatricula = new javax.swing.JMenuItem();
        menuProcesosMensualidad = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuAyudaContenidos = new javax.swing.JMenuItem();
        menuAyudaAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        menuArchivo.setMnemonic('f');
        menuArchivo.setText("Archivo");

        menuArchivoExportar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuArchivoExportar.setMnemonic('o');
        menuArchivoExportar.setText("Opciones");
        menuArchivoExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArchivoExportarActionPerformed(evt);
            }
        });
        menuArchivo.add(menuArchivoExportar);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setText("Exportar");
        menuArchivo.add(jMenuItem11);
        menuArchivo.add(jSeparator1);

        menuArchivoSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuArchivoSalir.setMnemonic('x');
        menuArchivoSalir.setText("Salir");
        menuArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArchivoSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuArchivoSalir);

        barraMenu.add(menuArchivo);

        menuMantenedores.setMnemonic('e');
        menuMantenedores.setText("Mantenedores");

        menuMantenedoresAlumnos.setMnemonic('t');
        menuMantenedoresAlumnos.setText("Alumnos");
        menuMantenedores.add(menuMantenedoresAlumnos);

        menuMantenedoresDocentes.setMnemonic('y');
        menuMantenedoresDocentes.setText("Docentes");
        menuMantenedoresDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMantenedoresDocentesActionPerformed(evt);
            }
        });
        menuMantenedores.add(menuMantenedoresDocentes);

        menuMantenedoresAdministrativos.setMnemonic('p');
        menuMantenedoresAdministrativos.setText("Administrativos");
        menuMantenedores.add(menuMantenedoresAdministrativos);

        menuMantenedoresAuxiliares.setMnemonic('d');
        menuMantenedoresAuxiliares.setText("Auxiliares");
        menuMantenedores.add(menuMantenedoresAuxiliares);

        barraMenu.add(menuMantenedores);

        menuInformes.setText("Informes");

        menuInformeNotas.setText("Notas");
        menuInformeNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInformeNotasActionPerformed(evt);
            }
        });
        menuInformes.add(menuInformeNotas);

        menuInformeAsistencia.setText("Asistencia");
        menuInformes.add(menuInformeAsistencia);
        menuInformes.add(jSeparator3);

        menuInformeMatricula.setText("Matrícula");
        menuInformes.add(menuInformeMatricula);

        menuInformeMensualidad.setText("Mensualidad");
        menuInformes.add(menuInformeMensualidad);

        barraMenu.add(menuInformes);

        menuProcesos.setText("Procesos");

        menuProcesosNotas.setText("Notas");
        menuProcesosNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProcesosNotasActionPerformed(evt);
            }
        });
        menuProcesos.add(menuProcesosNotas);

        menuProcesosAsistencia.setText("Asistencia");
        menuProcesos.add(menuProcesosAsistencia);
        menuProcesos.add(jSeparator4);

        menuProcesosMatricula.setText("Matrícula");
        menuProcesos.add(menuProcesosMatricula);

        menuProcesosMensualidad.setText("Mensualidad");
        menuProcesos.add(menuProcesosMensualidad);

        barraMenu.add(menuProcesos);

        menuAyuda.setMnemonic('h');
        menuAyuda.setText("Ayuda");

        menuAyudaContenidos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuAyudaContenidos.setMnemonic('c');
        menuAyudaContenidos.setText("Contenidos");
        menuAyuda.add(menuAyudaContenidos);

        menuAyudaAcercaDe.setMnemonic('a');
        menuAyudaAcercaDe.setText("Acerca de...");
        menuAyuda.add(menuAyudaAcercaDe);

        barraMenu.add(menuAyuda);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoSalirActionPerformed
        DialogoSalir ds = new DialogoSalir(this, rootPaneCheckingEnabled);
        ds.setVisible(true);
        
        if(ds.getReturnStatus() == DialogoSalir.RET_OK) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuArchivoSalirActionPerformed

    private void menuArchivoExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoExportarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuArchivoExportarActionPerformed

    private void menuInformeNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInformeNotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuInformeNotasActionPerformed

    private void menuProcesosNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesosNotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuProcesosNotasActionPerformed

    private void menuMantenedoresDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMantenedoresDocentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMantenedoresDocentesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaCurricular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaCurricular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaCurricular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaCurricular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaCurricular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuArchivoExportar;
    private javax.swing.JMenuItem menuArchivoSalir;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuItem menuAyudaAcercaDe;
    private javax.swing.JMenuItem menuAyudaContenidos;
    private javax.swing.JMenuItem menuInformeAsistencia;
    private javax.swing.JMenuItem menuInformeMatricula;
    private javax.swing.JMenuItem menuInformeMensualidad;
    private javax.swing.JMenuItem menuInformeNotas;
    private javax.swing.JMenu menuInformes;
    private javax.swing.JMenu menuMantenedores;
    private javax.swing.JMenuItem menuMantenedoresAdministrativos;
    private javax.swing.JMenuItem menuMantenedoresAlumnos;
    private javax.swing.JMenuItem menuMantenedoresAuxiliares;
    private javax.swing.JMenuItem menuMantenedoresDocentes;
    private javax.swing.JMenu menuProcesos;
    private javax.swing.JMenuItem menuProcesosAsistencia;
    private javax.swing.JMenuItem menuProcesosMatricula;
    private javax.swing.JMenuItem menuProcesosMensualidad;
    private javax.swing.JMenuItem menuProcesosNotas;
    // End of variables declaration//GEN-END:variables

}
